# Generated by Django 5.1.3 on 2024-12-08 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("author", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="captcha",
            name="captcha",
            field=models.CharField(max_length=4, verbose_name="验证码"),
        ),
        migrations.AlterField(
            model_name="captcha",
            name="create_time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="captcha",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="邮箱"),
        ),
    ]
