# Generated by Django 5.1.3 on 2024-12-13 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("author", "0002_alter_captcha_captcha_alter_captcha_create_time_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="user_head",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField(verbose_name="用户id")),
                (
                    "head_img",
                    models.ImageField(upload_to="head_img", verbose_name="头像"),
                ),
                ("user_name", models.CharField(max_length=20, verbose_name="用户名")),
            ],
        ),
    ]
