# Generated by Django 5.1.3 on 2024-12-13 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="circledata",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("image_name", models.CharField(max_length=200)),
                ("text", models.CharField(max_length=200)),
                ("x", models.IntegerField()),
                ("y", models.IntegerField()),
                ("r", models.IntegerField()),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                (
                    "label_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="annotation.label",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="polygondata",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("image_name", models.CharField(max_length=200)),
                ("text", models.CharField(max_length=200)),
                ("polygon", models.TextField(verbose_name="Polygon")),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                (
                    "label_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="annotation.label",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="rectdata",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("image_name", models.CharField(max_length=200)),
                ("text", models.CharField(max_length=200)),
                ("startx", models.IntegerField()),
                ("starty", models.IntegerField()),
                ("endx", models.IntegerField()),
                ("endy", models.IntegerField()),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                (
                    "label_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="annotation.label",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Annotation",
        ),
    ]
