# Generated by Django 5.1.5 on 2025-01-21 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotation", "0002_circledata_polygondata_rectdata_delete_annotation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rectdata",
            name="label_id",
        ),
        migrations.CreateModel(
            name="pencildata",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("image_name", models.CharField(max_length=200)),
                ("text", models.CharField(max_length=200)),
                ("pencil", models.TextField(max_length=200)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                (
                    "label_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="annotation.label",
                    ),
                ),
            ],
        ),
    ]
