# Generated by Django 5.1.5 on 2025-01-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotation", "0003_remove_rectdata_label_id_pencildata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rectdata",
            name="endx",
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name="rectdata",
            name="endy",
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name="rectdata",
            name="startx",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="rectdata",
            name="starty",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="rectdata",
            name="text",
            field=models.CharField(default="默认数据", max_length=200),
        ),
    ]
