# Generated by Django 5.1.5 on 2025-01-23 02:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotation", "0004_alter_rectdata_endx_alter_rectdata_endy_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="circledata",
            name="create_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 1, 23, 10, 28, 19, 699153)
            ),
        ),
        migrations.AlterField(
            model_name="pencildata",
            name="create_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 1, 23, 10, 28, 19, 700027)
            ),
        ),
        migrations.AlterField(
            model_name="polygondata",
            name="create_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 1, 23, 10, 28, 19, 699153)
            ),
        ),
        migrations.AlterField(
            model_name="rectdata",
            name="create_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 1, 23, 10, 28, 19, 699153)
            ),
        ),
    ]
