# Generated by Django 5.1.5 on 2025-01-23 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotation", "0005_alter_circledata_create_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="circledata",
            name="create_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 1, 23, 17, 19, 0, 336174)
            ),
        ),
        migrations.AlterField(
            model_name="pencildata",
            name="create_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 1, 23, 17, 19, 0, 337212)
            ),
        ),
        migrations.AlterField(
            model_name="polygondata",
            name="create_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 1, 23, 17, 19, 0, 336174)
            ),
        ),
        migrations.AlterField(
            model_name="rectdata",
            name="create_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 1, 23, 17, 19, 0, 336174)
            ),
        ),
        migrations.AlterField(
            model_name="rectdata",
            name="image_name",
            field=models.CharField(default="默认名字", max_length=200),
        ),
    ]
