# Generated by Django 5.1.5 on 2025-01-23 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotation", "0006_alter_circledata_create_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="circledata",
            name="label_id",
        ),
        migrations.RemoveField(
            model_name="pencildata",
            name="label_id",
        ),
        migrations.RemoveField(
            model_name="polygondata",
            name="label_id",
        ),
        migrations.AlterField(
            model_name="circledata",
            name="create_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 1, 23, 22, 17, 34, 858406)
            ),
        ),
        migrations.AlterField(
            model_name="pencildata",
            name="create_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 1, 23, 22, 17, 34, 858406)
            ),
        ),
        migrations.AlterField(
            model_name="polygondata",
            name="create_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 1, 23, 22, 17, 34, 858406)
            ),
        ),
        migrations.AlterField(
            model_name="rectdata",
            name="create_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 1, 23, 22, 17, 34, 858406)
            ),
        ),
    ]
