# Generated by Django 5.1.5 on 2025-01-24 03:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotation", "0007_remove_circledata_label_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="circledata",
            name="create_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 1, 24, 11, 25, 35, 200460)
            ),
        ),
        migrations.AlterField(
            model_name="pencildata",
            name="create_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 1, 24, 11, 25, 35, 200460)
            ),
        ),
        migrations.AlterField(
            model_name="pencildata",
            name="pencil",
            field=models.TextField(verbose_name="Pencil"),
        ),
        migrations.AlterField(
            model_name="polygondata",
            name="create_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 1, 24, 11, 25, 35, 200460)
            ),
        ),
        migrations.AlterField(
            model_name="rectdata",
            name="create_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 1, 24, 11, 25, 35, 199476)
            ),
        ),
    ]
