# Generated by Django 5.1.5 on 2025-01-26 02:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotation", "0008_alter_circledata_create_time_and_more"),
        ("app01", "0008_user_image_isailabeled_user_image_islabeled"),
    ]

    operations = [
        migrations.AddField(
            model_name="circledata",
            name="imageid",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="app01.user_image",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pencildata",
            name="imageid",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="app01.user_image",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="polygondata",
            name="imageid",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="app01.user_image",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rectdata",
            name="imageid",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="app01.user_image",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="circledata",
            name="create_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 1, 26, 10, 33, 46, 96767)
            ),
        ),
        migrations.AlterField(
            model_name="pencildata",
            name="create_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 1, 26, 10, 33, 46, 96767)
            ),
        ),
        migrations.AlterField(
            model_name="polygondata",
            name="create_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 1, 26, 10, 33, 46, 96767)
            ),
        ),
        migrations.AlterField(
            model_name="rectdata",
            name="create_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 1, 26, 10, 33, 46, 96767)
            ),
        ),
    ]
