# Generated by Django 5.1.3 on 2024-12-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="base64image",
            name="image",
            field=models.ImageField(
                default="default.jpg", upload_to="images/%Y/%m/%d", verbose_name="图片"
            ),
        ),
    ]
