# Generated by Django 5.1.3 on 2024-12-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0003_remove_base64image_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="product_images/")),
            ],
        ),
        migrations.DeleteModel(
            name="Base64Image",
        ),
    ]
