# Generated by Django 5.1.3 on 2024-12-12 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0005_product_image_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="author",
            field=models.CharField(default="admin", max_length=100),
        ),
        migrations.AddField(
            model_name="product",
            name="time",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
