# Generated by Django 5.1.3 on 2024-12-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0007_user_image_delete_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_image",
            name="isailabeled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user_image",
            name="islabeled",
            field=models.BooleanField(default=False),
        ),
    ]
